$primary = rgb(ea9a97)
$surface = rgb(232136)
$secondary = rgb(9ccfd8)
$error = rgb(eb6f92)
$tertiary = rgb(3e8fb0)
$surface_lowest = rgb(27253b)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
